# Generated by Django 5.1 on 2024-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='anwser',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='resposta'),
        ),
    ]
